// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Youz_Backend.DB;

#nullable disable

namespace Youz_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118211559_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Youz_Backend.DB.Models.DescriptionChunk", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LandmarkID")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("TextEmbedding")
                        .IsRequired()
                        .HasColumnType("vector(3072)");

                    b.HasKey("ID");

                    b.HasIndex("LandmarkID");

                    b.ToTable("DescriptionChunks");
                });

            modelBuilder.Entity("Youz_Backend.DB.Models.ImageChunk", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Vector>("ImageEmbedding")
                        .IsRequired()
                        .HasColumnType("vector(3072)");

                    b.Property<Guid>("LandmarkID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("LandmarkID");

                    b.ToTable("ImageChunks");
                });

            modelBuilder.Entity("Youz_Backend.DB.Models.Landmark", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Landmarks");
                });

            modelBuilder.Entity("Youz_Backend.DB.Models.DescriptionChunk", b =>
                {
                    b.HasOne("Youz_Backend.DB.Models.Landmark", "Landmark")
                        .WithMany("DescriptionChunks")
                        .HasForeignKey("LandmarkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Landmark");
                });

            modelBuilder.Entity("Youz_Backend.DB.Models.ImageChunk", b =>
                {
                    b.HasOne("Youz_Backend.DB.Models.Landmark", "Landmark")
                        .WithMany("ImageChunks")
                        .HasForeignKey("LandmarkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Landmark");
                });

            modelBuilder.Entity("Youz_Backend.DB.Models.Landmark", b =>
                {
                    b.Navigation("DescriptionChunks");

                    b.Navigation("ImageChunks");
                });
#pragma warning restore 612, 618
        }
    }
}
